summarize_job_post_task:
  description: >
    Given the following job posting, extract the top 5 most important skills or technologies required.
    Be concise and only return a bullet point list.
  expected_output: >
    - Skill 1
    - Skill 2
    - Skill 3
    - Skill 4
    - Skill 5
  agent: JobPostSummarizerAgent

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
